import BlogList from '@/components/BlogList';
import SubscribeNewsletter from '@/components/SubscribeNewsletter';
import Head from 'next/head'

export async function getStaticProps(context) {
    const fetchParams = {
        method: "GET",
        headers: {
            "content-type": "Application/json",
            'Authorization': `Bearer ${process.env.STRAPITOKEN}`
        },
    };
    const res = await fetch(`${process.env.STRAPIBASEURL}/api/blogposts`, fetchParams);
    const data = await res.json();
    return {
        props: { ...data }
    };
}

export default function Home(data) {
    return (
        <>
            <Head>
                <title>Blog - Larry Rowbs Foundation</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <BlogList data={data.data}/>
                <SubscribeNewsletter />
            </main>
        </>
    )
}
