import Benefits from '@/components/homepage/Benefits'
import HarmsCaused from '@/components/homepage/HarmsCaused'
import OurMission from '@/components/homepage/OurMission'
import OurWork from '@/components/homepage/OurWork'
import TextileWasteCarousel from '@/components/homepage/TextileWasteCarousel'
import WhatsHappening from '@/components/homepage/WhatsHappening'
import Partners from '@/components/homepage/Partners'
import SubscribeNewsletter from '@/components/SubscribeNewsletter'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Larry Rowbs Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <TextileWasteCarousel />
        <WhatsHappening />
        <HarmsCaused />
        <OurWork />
        <OurMission />
        <Benefits />
        <Partners />
        <SubscribeNewsletter />
      </div>
    </>
  )
}
