import OurWork from '@/components/homepage/OurWork'
import WhatsHappening from '@/components/homepage/WhatsHappening'
import Partners from '@/components/homepage/Partners'
import Head from 'next/head'

import { Button, Link } from "@nextui-org/react";
import YoutubeVideo from '@/components/Youtube'

const benefits = [
    {
        title: "More Jobs",
        icon: "/iconmonstr-party-22.svg",
        description: <>Sustainable fashion gives a boost to the economies of underdeveloped areas. It creates new jobs and <b>fair-wage</b> opportunities.</>
    },
    {
        title: "Better Health",
        icon: "/basketball-player-scoring-svgrepo-com.svg",
        description: <>Fast fashion harms the environment and threatens health with toxic chemicals. We&apos;re committed to safe, <b>sustainable</b> clothing for a greener, <b>healthier</b> world.</>
    },
    {
        title: "Free Education",
        icon: "/iconmonstr-school-30.svg",
        description: <>Fashion school costs <b>$$$</b>. We will fund a <b>Charitable Fashion School</b> with revenue from selling sustainable fashion, offering free education to drive industry change.</>
    }
]

export default function Home() {
    return (
        <>
            <Head>
                <title>Home - Larry Rowbs Foundation</title>
                <meta name="description" content="Larry Rowbs Foundation is a registered non-governmental organization working on mitigating the harms of the fast-fashion industry" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col pt-18 sm:pt-24 md:pt-30 gap-16 sm:gap-24 md:gap-30'>
                <div className='px-3 text-center flex flex-col items-center justify-center gap-8 md:gap-12'>
                    <div className='text-3xl sm:text-4xl md:text-5xl font-bold bg-gradient-to-r from-stone-700 to-emerald-600 bg-clip-text text-transparent'>
                        Making fashion sustainable<br />
                        - one step at a time
                    </div>
                    <div className='text-lg sm:text-xl'>
                        Larry Rowbs Foundation is recycling the waste generated by fast-fashion into 100% biodegradable products,<br />
                        ensuring a greener earth and empowering lives of fashion workers.
                    </div>
                    <Button
                        size='lg'
                        className='bg-green-600 text-white font-bold text-lg sm:text-xl'
                        href="/donate"
                        as={Link}
                    >Donate</Button>
                </div>
                <div className='w-11/12 sm:w-3/4 md:w-3/5 mx-auto drop-shadow-lg md:drop-shadow-[0_35px_35px_rgba(0,0,0,0.25)]'>
                    <YoutubeVideo videoId="sNYn-M6TfII" />
                </div>
                <div className='w-11/12 sm:w-3/4 mx-auto flex flex-col gap-12'>
                    <div className='grid grid-cols-1 md:grid-cols-3 gap-12 sm:gap-5 items-start'>
                        {
                            benefits.map((benefit, index) => {
                                return <div key={index} className='flex flex-col gap-3 justify-center'>
                                    <img
                                        src={benefit.icon}
                                        alt={benefit.title}
                                        width={60}
                                        height={60}
                                        className='max-w-[50%] m-auto aspect-1'
                                    />
                                    <h2 className='capitalize font-bold text-xl sm:text-2xl md:text-3xl text-center'>{benefit.title}</h2>
                                    <p
                                        className='text-center text-lg'
                                    >{benefit.description}</p>
                                </div>
                            })
                        }
                    </div>
                    <div className='flex justify-center items-center'>
                        <Button
                            size='lg'
                            className='bg-green-700 text-slate-50 font-bold text-lg sm:text-xl'
                            as={Link}
                            href="/blog"
                        >Read More</Button>
                    </div>
                </div>
                <WhatsHappening />
                <OurWork />
                <Partners />
            </div>
        </>
    )
}
