export const APP_ENV = process.env.NODE_ENV

export const ngoDetails = {
    name: 'Larry Rowbs Foundation',
    tagline: 'Making fashion sustainable - a step at a time',
    description:
        'Larry Rowbs Foundation is dedicated to recycling waste generated by the fast fashion industry into 100% biodegradable products, ensuring a greener Earth and empowering the lives of fashion workers worldwide.',
    keywords: [
        'NGO',
        'non-profit',
        'sustainable fashion',
        'recycling',
        'biodegradable products',
        'fashion waste',
        'ethical fashion',
        'fair wages',
        'clothing donation',
        'eco-friendly',
        'fashion industry reform',
    ],
    registrationNumber: 'E-0014172(THN)',
    logo: `logo.webp`,
    contact: {
        addresses: [
            {
                type: 'registration',
                label: 'Registration Address',
                description: 'For Official / Legal Purposes',
                address:
                    '2459 Sugar Bottom Rd Furlong, Pennsylvania United States - 18925',
            },
        ],
        email: 'info@larryrowbsfoundation.org',
        phone: '+01 605 954 8885',
        whatsapp: '+016059548885',
        website: 'https://www.larryrowbsfoundation.ngo',
    },
    twitterHandle: '@larryrowbsfoundation',
    twitterCardType: 'summary_large_image',
} as const

export const ORG_ID = 'e6eed2cd-ac4a-4db4-9dfb-938f96c649d5'

export const DEFAULT_CAMPAIGN = '935203bf-247a-4939-b652-c0a95277fa41'
export const adminPanelLink = 'https://k34a.vercel.app'
