import OurWork from '@/components/homepage/OurWork'
import WhatsHappening from '@/components/homepage/WhatsHappening'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Larry Rowbs Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <WhatsHappening />
        <OurWork />
      </div>
    </>
  )
}
